### ISSUE TITLE
Some articles are not available through their links

### ISSUE THREAD

**Issue by alikatgh** [facundoolano/software-papers#14]
List of articles that are not available

 https://www.ic.tu-berlin.de/fileadmin/fg121/Source-Coding_WS12/selected-readings/10_04051119.pdf
 http://www-m3.ma.tum.de/foswiki/pub/MN0506/WebHome/dijkstra.pdf
 http://www0.cs.ucl.ac.uk/staff/m.handley/papers/only-just-works.pdf
 https://www.ic.tu-berlin.de/fileadmin/fg121/Source-Coding_WS12/selected-readings/10_04051119.pdf
 https://www.ic.tu-berlin.de/fileadmin/fg121/Source-Coding_WS12/selected-readings/10_04051119.pdf
 http://www-m3.ma.tum.de/foswiki/pub/MN0506/WebHome/dijkstra.pdf
 http://sei.pku.edu.cn/~yaoguo/PhDReading07/parnas-review.pdf

**Comment by facundoolano** [comment]
I was able to download the `only-just-works` one.  You also have some duplicates over there, so we're missing 3 papers (dijkstra, parnas and huffman). I'll fix those.

**Comment by facundoolano** [comment]
this should be fixed now
